// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "FaceIdentify.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

class FaceIdentifyHandler : virtual public FaceIdentifyIf {
 public:
  FaceIdentifyHandler() {
    // Your initialization goes here
  }

  void FI_add_face_database(const std::string& imagename) {
    // Your implementation goes here
    printf("FI_add_face_database\n");
  }

  int32_t FI_del_face_database(const std::string& uid) {
    // Your implementation goes here
    printf("FI_del_face_database\n");
  }

  int32_t FI_update_face_database(const std::string& imagename) {
    // Your implementation goes here
    printf("FI_update_face_database\n");
  }

  int32_t FI_find_user_info(const std::string& uid) {
    // Your implementation goes here
    printf("FI_find_user_info\n");
  }

  int32_t FI_find_group_users(const std::string& group_id) {
    // Your implementation goes here
    printf("FI_find_group_users\n");
  }

  void FI_face_database_identify(std::string& _return, const std::string& group_id, const std::string& imagename) {
    // Your implementation goes here
    printf("FI_face_database_identify\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<FaceIdentifyHandler> handler(new FaceIdentifyHandler());
  shared_ptr<TProcessor> processor(new FaceIdentifyProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

