/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef identify_CONSTANTS_H
#define identify_CONSTANTS_H

#include "identify_types.h"



class identifyConstants {
 public:
  identifyConstants();

};

extern const identifyConstants g_identify_constants;



#endif
