/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "identify_constants.h"



const identifyConstants g_identify_constants;

identifyConstants::identifyConstants() {
}



